---
http_interactions:
- request:
    method: get
    uri: https://www.pivotaltracker.com/services/v5/projects/367813
    body:
      encoding: US-ASCII
      string: ''
    headers:
      X-Trackertoken:
      - ''
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Status:
      - 200 OK
      X-Tracker-Project-Version:
      - '79039'
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 24dedc0e46ac2fb9505b384fdf0abf5d
      X-Runtime:
      - '0.054247'
      Date:
      - Tue, 17 Mar 2015 22:19:03 GMT
      X-Rack-Cache:
      - miss
      X-Powered-By:
      - Phusion Passenger 4.0.41
      Server:
      - nginx/1.6.0 + Phusion Passenger 4.0.41
      Access-Control-Allow-Origin:
      - "*"
      Access-Control-Allow-Credentials:
      - 'false'
      Access-Control-Allow-Methods:
      - GET, POST, PUT, DELETE, OPTIONS
      Access-Control-Allow-Headers:
      - X-TrackerToken,DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Tracker-Warn-Unless-Project-Version-Is
      X-Tracker-Client-Pinger-Interval:
      - '12'
    body:
      encoding: ASCII-8BIT
      string: '{"id":367813,"kind":"project","name":"Departments and policy (Dev)","version":79039,"iteration_length":2,"week_start_day":"Wednesday","point_scale":"0,1,2,3,5,8","point_scale_is_custom":false,"bugs_and_chores_are_estimatable":false,"automatic_planning":true,"enable_tasks":true,"time_zone":{"kind":"time_zone","olson_name":"Europe/London","offset":"+00:00"},"velocity_averaged_over":1,"number_of_done_iterations_to_show":12,"has_google_domain":false,"description":"The
        \"departments and policy\" section of GOV.UK, including publishing tools for
        government","enable_incoming_emails":true,"initial_velocity":25,"public":true,"atom_enabled":true,"start_date":"2011-09-14","start_time":"2011-09-13T23:00:00Z","created_at":"2011-09-11T19:50:57Z","updated_at":"2015-01-13T00:06:18Z","account_id":309645,"current_iteration_number":92,"enable_following":true}'
    http_version: 
  recorded_at: Tue, 17 Mar 2015 22:19:04 GMT
recorded_with: VCR 2.9.3
